# Copyright (c) 2025 - 2026 Eric Sabo
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

function _BB_cache(F::CTFieldTypes, n::Int)
    return Dict{Symbol, Any}(
        :F => F,
        :char_vec => zzModRingElem[],
        :d => missing,
        :l_bound => 1,
        :u_bound => n,
    )
end

function _check_BB_pair(a, b)
    parent(a) == parent(b) ||
        throw(ArgumentError("The defining polynomials must have the same parent."))
end

function _standard_BB_periods(R)
    S = base_ring(R)
    vars = gens(S)
    length(vars) == 2 ||
        throw(ArgumentError("The quotient must be over a polynomial ring in two variables."))

    periods = fill(0, 2)
    modulus_generators = gens(modulus(R))
    length(modulus_generators) == 2 ||
        throw(ArgumentError("The quotient ideal must have exactly two generators."))
    for f in modulus_generators
        exps = collect(exponents(f))
        nonconstant = filter(e -> !iszero(e), exps)
        length(nonconstant) == 1 ||
            throw(ArgumentError("The quotient must have moduli x^l - 1 and y^m - 1."))
        e = only(nonconstant)
        nonzero_positions = findall(!iszero, e)
        length(nonzero_positions) == 1 ||
            throw(ArgumentError("The quotient must have moduli x^l - 1 and y^m - 1."))
        i = only(nonzero_positions)
        d = e[i]
        d > 0 && f == vars[i]^d - 1 ||
            throw(ArgumentError("The quotient must have moduli x^l - 1 and y^m - 1."))
        iszero(periods[i]) ||
            throw(ArgumentError("The quotient contains duplicate coordinate moduli."))
        periods[i] = d
    end
    all(>(0), periods) ||
        throw(ArgumentError("The quotient must bound both polynomial variables."))
    return periods[1], periods[2]
end

"""
    InfiniteBBCode(a::CTLRPolyElem, b::CTLRPolyElem)

Return the algebraic bivariate-bicycle datum defined by Laurent polynomials
`a` and `b`. A finite lattice must be supplied to `BBCode` before stabilizer
matrices or finite code parameters exist.
"""
function InfiniteBBCode(a::CTLRPolyElem, b::CTLRPolyElem)
    _check_BB_pair(a, b)
    LR = parent(a)
    length(symbols(LR)) == 2 ||
        throw(ArgumentError("The polynomials must be in two Laurent variables."))
    return InfiniteBBCode(LR, base_ring(base_ring(LR)), a, b)
end

"""
    BBCode(a, b)

Construct a standard finite BB code from elements of
`F[x,y]/(x^l - 1, y^m - 1)`.
"""
function BBCode(a::T, b::T) where {
    T <: Union{MPolyQuoRingElem{FqMPolyRingElem},
               MPolyQuoRingElem{fpMPolyRingElem}}
}
    _check_BB_pair(a, b)
    R = parent(a)
    F = base_ring(base_ring(R))
    order(F) == 2 ||
        throw(ArgumentError("BB codes are currently implemented over binary fields."))
    l, m = _standard_BB_periods(R)
    Q, _ = quo(R, ideal(R, [a, b]))
    k = 2 * vector_space_dimension(Q)
    n = 2 * l * m
    result = BBCode(R, F, a, b, (l, 0), (0, m), nothing, n, k,
                    false, :bivariate_quotient, _BB_cache(F, n))
    return _seed_quantum_singleton_bound!(result)
end

"""
    BBCode(a::CTLRPolyElem, b::CTLRPolyElem, a1, a2)

Construct a finite twisted BB code on the Laurent lattice generated by `a1`
and `a2`.
"""
function BBCode(a::CTLRPolyElem, b::CTLRPolyElem,
                a1::Tuple{Int, Int}, a2::Tuple{Int, Int})
    _check_BB_pair(a, b)
    LR = parent(a)
    length(symbols(LR)) == 2 ||
        throw(ArgumentError("The polynomials must be in two Laurent variables."))
    det = a1[1] * a2[2] - a1[2] * a2[1]
    iszero(det) &&
        throw(ArgumentError("The lattice vectors must be linearly independent."))
    F = base_ring(base_ring(LR))
    order(F) == 2 ||
        throw(ArgumentError("BB codes are currently implemented over binary fields."))

    R2 = Oscar._polyringquo(LR)
    R = codomain(R2)
    x, y = gens(LR)
    lattice = [x^a1[1] * y^a1[2] - 1,
               x^a2[1] * y^a2[2] - 1]
    Q_lattice, _ = quo(R, ideal(R, R2.(lattice)))
    n = 2 * length(monomial_basis(Q_lattice))
    Q_code, _ = quo(R, ideal(R, R2.([a, b, lattice...])))
    k = 2 * vector_space_dimension(Q_code)
    twisted = !iszero(a1[2]) || !iszero(a2[1])
    result = BBCode(LR, F, a, b, a1, a2, nothing, n, k, twisted,
                    :laurent_lattice, _BB_cache(F, n))
    return _seed_quantum_singleton_bound!(result)
end

"""
    BBCode(a::CTLRPolyElem, b::CTLRPolyElem, l::Int, m::Int)

Construct an untwisted finite BB code on an `l` by `m` torus.
"""
function BBCode(a::CTLRPolyElem, b::CTLRPolyElem, l::Int, m::Int)
    l > 0 || throw(DomainError(l, "The x period must be positive."))
    m > 0 || throw(DomainError(m, "The y period must be positive."))
    S = BBCode(a, b, (l, 0), (0, m))
    S.twisted = false
    return S
end

"""
    BBCode(a::CTPolyRingElem, b::CTPolyRingElem, N::Int)

Construct the coprime univariate form modulo `z^N - 1`.
"""
function BBCode(a::CTPolyRingElem, b::CTPolyRingElem, N::Int)
    _check_BB_pair(a, b)
    N > 0 || throw(DomainError(N, "The period must be positive."))
    R = parent(a)
    F = base_ring(R)
    order(F) == 2 ||
        throw(ArgumentError("BB codes are currently implemented over binary fields."))
    z = gen(R)
    g = gcd(a, gcd(b, z^N - 1))
    n = 2 * N
    result = BBCode(R, F, a, b, nothing, nothing, N, n, 2 * degree(g),
                    false, :univariate, _BB_cache(F, n))
    return _seed_quantum_singleton_bound!(result)
end

"""
    BBCode(a::ResElem, b::ResElem)

Construct the coprime univariate form from elements of `F[z]/(z^N - 1)`.
"""
function BBCode(a::T, b::T) where {T <: ResElem}
    _check_BB_pair(a, b)
    R = parent(a)
    P = base_ring(R)
    length(gens(P)) == 1 ||
        throw(ArgumentError("The residue ring must be univariate."))
    F = base_ring(P)
    order(F) == 2 ||
        throw(ArgumentError("BB codes are currently implemented over binary fields."))
    f = modulus(R)
    N = degree(f)
    f == gen(P)^N - 1 ||
        throw(ArgumentError("The residue modulus must be z^N - 1."))
    g = gcd(lift(a), gcd(lift(b), f))
    n = 2 * N
    result = BBCode(R, F, a, b, nothing, nothing, N, n, 2 * degree(g),
                    false, :univariate_residue, _BB_cache(F, n))
    return _seed_quantum_singleton_bound!(result)
end

function _evaluate_standard_BB_matrices!(S::BBCode)
    l, m = S.a1[1], S.a2[2]
    F = S.F
    x_shift = matrix(F, [mod1(i + 1, l) == j ? 1 : 0
                         for i in 1:l, j in 1:l]) ⊗ identity_matrix(F, m)
    y_shift = identity_matrix(F, l) ⊗
              matrix(F, [mod1(i + 1, m) == j ? 1 : 0
                         for i in 1:m, j in 1:m])

    function evaluate(f)
        M = zero_matrix(F, l * m, l * m)
        p = lift(f)
        for (c, e) in zip(coefficients(p), exponents(p))
            M += c * x_shift^e[1] * y_shift^e[2]
        end
        return M
    end
    A, B = evaluate(S.a), evaluate(S.b)
    H_X = hcat(A, B)
    H_Z = hcat(transpose(B), transpose(A))
    S.cache[:H_X] = S.cache[:X_stabs] = H_X
    S.cache[:H_Z] = S.cache[:Z_stabs] = H_Z
end

function _evaluate_laurent_BB_matrices!(S::BBCode)
    R2 = Oscar._polyringquo(S.R)
    R = codomain(R2)
    x, y = gens(S.R)
    anti = hom(S.R, S.R, [x^-1, y^-1])
    a_R2, b_R2 = R2(S.a), R2(S.b)
    a_anti_R2, b_anti_R2 = R2(anti(S.a)), R2(anti(S.b))
    lattice = [x^S.a1[1] * y^S.a1[2] - 1,
               x^S.a2[1] * y^S.a2[2] - 1]
    Q, phi = quo(R, ideal(R, R2.(lattice)))
    mono = monomial_basis(Q)
    q = length(mono)
    left = Dict(mono[i] => i for i in 1:q)
    right = Dict(mono[i] => i + q for i in 1:q)
    H_X = zero_matrix(S.F, q, 2q)
    H_Z = zero_matrix(S.F, q, 2q)
    one_F = S.F(1)
    for (row, edge) in enumerate(mono)
        for term in terms(simplify(phi(edge * a_R2)).f)
            H_X[row, right[term]] = one_F
        end
        for term in terms(simplify(phi(edge * b_R2)).f)
            H_X[row, left[term]] = one_F
        end
        for term in terms(simplify(phi(edge * b_anti_R2)).f)
            H_Z[row, right[term]] = one_F
        end
        for term in terms(simplify(phi(edge * a_anti_R2)).f)
            H_Z[row, left[term]] = one_F
        end
    end
    S.cache[:H_X] = S.cache[:X_stabs] = H_X
    S.cache[:H_Z] = S.cache[:Z_stabs] = H_Z
end

function _evaluate_univariate_BB_matrices!(S::BBCode)
    N, F = S.N, S.F
    a = S.representation == :univariate_residue ? lift(S.a) : S.a
    b = S.representation == :univariate_residue ? lift(S.b) : S.b
    R = parent(a)
    z = gen(R)
    modulus_polynomial = z^N - 1
    A = zero_matrix(F, N, N)
    B = zero_matrix(F, N, N)
    for i in 1:N
        a_shift = (z^(i - 1) * a) % modulus_polynomial
        b_shift = (z^(i - 1) * b) % modulus_polynomial
        for d in 0:(N - 1)
            A[i, d + 1] = coeff(a_shift, d)
            B[i, d + 1] = coeff(b_shift, d)
        end
    end
    H_X = hcat(A, B)
    H_Z = hcat(transpose(B), transpose(A))
    S.cache[:H_X] = S.cache[:X_stabs] = H_X
    S.cache[:H_Z] = S.cache[:Z_stabs] = H_Z
end

function _evaluate_BB_matrices!(S::BBCode)
    haskey(S.cache, :X_stabs) && return
    if S.representation == :bivariate_quotient
        _evaluate_standard_BB_matrices!(S)
    elseif S.representation == :laurent_lattice
        _evaluate_laurent_BB_matrices!(S)
    else
        _evaluate_univariate_BB_matrices!(S)
    end
end

function X_stabilizers(S::BBCode)
    _evaluate_BB_matrices!(S)
    return S.cache[:X_stabs]
end

function Z_stabilizers(S::BBCode)
    _evaluate_BB_matrices!(S)
    return S.cache[:Z_stabs]
end

function stabilizers(S::BBCode; standform::Bool = false)
    _evaluate_BB_matrices!(S)
    return invoke(stabilizers, Tuple{AbstractSubsystemCode}, S;
                  standform = standform)
end

character_vector(S::BBCode) = S.cache[:char_vec]
defining_polynomials(S::Union{BBCode, InfiniteBBCode}) = S.a, S.b
twist_vectors(S::BBCode) =
    isnothing(S.a1) ? throw(ArgumentError("The univariate form has no chosen 2D lattice vectors.")) :
    (S.a1, S.a2)
Laurent_polynomial_ring(S::InfiniteBBCode) = S.LR
Laurent_polynomial_ring(S::BBCode) =
    S.representation == :laurent_lattice ? S.R :
    throw(ArgumentError("This BB code was not constructed over a Laurent ring."))
polynomial_ring(S::BBCode) = S.R

function maximum_dimension(S::InfiniteBBCode)
    R2 = Oscar._polyringquo(S.LR)
    R = codomain(R2)
    Q, _ = quo(R, ideal(R, R2.([S.a, S.b])))
    return 2 * vector_space_dimension(Q)
end

function is_pure(S::BBCode)
    if S.representation == :laurent_lattice
        R2 = Oscar._polyringquo(S.R)
        R = codomain(R2)
        x, y = gens(S.R)
        lattice = [x^S.a1[1] * y^S.a1[2] - 1,
                   x^S.a2[1] * y^S.a2[2] - 1]
        Q, phi = quo(R, ideal(R, R2.(lattice)))
        I_a = ideal(Q, [phi(R2(S.a))])
        I_b = ideal(Q, [phi(R2(S.b))])
    else
        Q = parent(S.a)
        I_a = ideal(Q, [S.a])
        I_b = ideal(Q, [S.b])
    end
    return I_a ∩ I_b == I_a * I_b
end

function Base.show(io::IO, S::InfiniteBBCode)
    print(io, "Infinite BB code datum over $(S.LR) with a = $(S.a), b = $(S.b)")
end

function Base.show(io::IO, S::BBCode)
    kind = S.twisted ? "twisted " : ""
    print(io, "$(kind)BB code [[$(S.n), $(S.k)]]_$(order(S.F))")
end
