# Copyright (c) 2023 - 2026 Eric Sabo, Benjamin Ide
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

#############################
        # constructors
#############################

"""
$(TYPEDSIGNATURES)

Return the Plotkin (u | u + v)-construction with `u ∈ C1` and `v ∈ C2`.
Evaluates lazily without eagerly building the generator matrices.
"""
function u_u_plus_v(C1::AbstractLinearCode, C2::AbstractLinearCode)
    C1.F == C2.F || throw(ArgumentError("Base field must be the same in the Plotkin (u|u + v)-construction."))
    C1.n == C2.n || throw(ArgumentError("Both codes must have the same length in the Plotkin (u|u + v)-construction."))

    n_new = 2 * C1.n
    k_new = C1.k + C2.k
    
    # O(1) Distance bounds calculation
    if ismissing(C1.d) || ismissing(C2.d)
        d_new = missing
        lb = min(2 * C1.l_bound, C2.l_bound)
        ub = min(2 * C1.u_bound, C2.u_bound)
    else
        d_new = min(2 * C1.d, C2.d)
        lb, ub = d_new, d_new
    end

    cache = Dict{Symbol, Any}()
    return PlotkinCode(C1, C2, C1.F, n_new, k_new, d_new, lb, ub, cache)
end
Plotkin_construction(C1::AbstractLinearCode, C2::AbstractLinearCode) = u_u_plus_v(C1, C2)

"""
$(TYPEDSIGNATURES)

Return the code generated by the (u + w | v + w | u + v + w)-construction.
"""
function u_plus_w_v_plus_w_u_plus_v_plus_w(C1::AbstractLinearCode, C2::AbstractLinearCode)
    C1.F == C2.F || throw(ArgumentError("All codes must be over the same base ring in the (u + w | v + w | u + v + w)-construction."))
    C1.n == C2.n || throw(ArgumentError("All codes must be the same length in the (u + w | v + w | u + v + w)-construction."))

    G1 = generator_matrix(C1)
    G2 = generator_matrix(C2)
    Z = zero_matrix(C1.F, C1.k, C1.n)
    
    G_new = vcat(hcat(G1, Z,  G1),
                 hcat(G2, G2, G2),
                 hcat(Z,  G1, G1))
                 
    # Rely on the standard lazy constructor
    return LinearCode(G_new)
end

# ==============================================================================
# BROUWER'S RECURSIVE CONSTRUCTIONS (A, B, Y1, B2)
# ==============================================================================

"""
$(TYPEDSIGNATURES)

Return the residue code of `C` with respect to a codeword `c` (Construction A).
If `c` has weight `w`, this produces an `[n - w, k - 1, d']` code where 
`d' >= d - w + w / q`.
"""
function construction_A(C::AbstractLinearCode, c::Union{Vector{Int}, Vector{<:CTFieldElem}})
    c ∈ C || throw(ArgumentError("The vector must be a codeword of C."))
    
    # Find the support (indices of non-zero elements)
    S = findall(!iszero, c)
    w = length(S)
    w > 0 || throw(ArgumentError("Cannot apply Construction A using the zero codeword."))
    
    # Shortening on the first index of the support drops the dimension to k - 1
    # Puncturing on the remaining support coordinates removes the rest of the word
    C_short = shorten(C, S[1])
    C_res = puncture(C_short, S[2:end])
    
    # Inject theoretical Griesmer step bounds
    q = order(C.F)
    base_d = ismissing(C.d) ? C.l_bound : C.d
    d_lower = base_d - w + ceil(Int, w / q)
    
    # Safely clamp and apply the theoretical bound
    if d_lower > C_res.l_bound
        C_res.l_bound = min(d_lower, C_res.u_bound)
    end
    
    return C_res
end
residue_code(C::AbstractLinearCode, c) = construction_A(C, c)

"""
$(TYPEDSIGNATURES)

Return the code obtained by applying Construction B (also known as Construction Y1) 
using a codeword `h` of the dual code. Shortens `C` on the support of `h`, 
dropping the dimension by `s - 1` instead of `s`.
"""
function construction_B(C::AbstractLinearCode, h::Union{Vector{Int}, Vector{<:CTFieldElem}})
    h ∈ dual(C) || throw(ArgumentError("The vector must be a codeword of the dual of C."))
    
    S = findall(!iszero, h)
    s = length(S)
    s > 0 || throw(ArgumentError("Cannot apply Construction B using the zero codeword."))
    
    # The mathematical properties of shortening on a dual word guarantees 
    # the dimension drops by at most s - 1. Distance is preserved.
    C_new = shorten(C, S)
    
    base_d = ismissing(C.d) ? C.l_bound : C.d
    if base_d > C_new.l_bound
        C_new.l_bound = min(base_d, C_new.u_bound)
    end
    
    return C_new
end
construction_Y1(C::AbstractLinearCode, h) = construction_B(C, h)
construction_Y(C::AbstractLinearCode, h) = construction_B(C, h)

"""
$(TYPEDSIGNATURES)

Return the code obtained by applying Construction B2 to a binary code `C` 
using a dual codeword `h` of weight `s` and a parameter `j` such that `2j + 1 < s`.
"""
function construction_B2(C::AbstractLinearCode, h::Union{Vector{Int}, Vector{<:CTFieldElem}}, j::Int)
    Int(order(C.F)) == 2 || throw(ArgumentError("Construction B2 is only defined for binary codes."))
    h ∈ dual(C) || throw(ArgumentError("The vector must be a codeword of the dual of C."))
    
    S = findall(!iszero, h)
    s = length(S)
    2j + 1 < s || throw(ArgumentError("Parameter j must satisfy 2j + 1 < weight(h) (currently $s)."))
    j >= 0 || throw(ArgumentError("Parameter j must be non-negative."))
    
    # Partition the support: shorten on the first part, puncture on the second
    T = S[1 : s - 2j - 1]
    U = S[s - 2j : end]
    
    C_short = shorten(C, T)
    C_new = puncture(C_short, U)
    
    # Mathematical guarantee: puncturing 2j + 1 coordinates here only drops weight by 2j
    base_d = ismissing(C.d) ? C.l_bound : C.d
    d_lower = base_d - 2j
    
    if d_lower > C_new.l_bound
        C_new.l_bound = min(d_lower, C_new.u_bound)
    end
    
    return C_new
end

"""
$(TYPEDSIGNATURES)

Return the code generated by the construction X procedure.
"""
function construction_X(C1::AbstractLinearCode, C2::AbstractLinearCode, C3::AbstractLinearCode)
    C1 ⊆ C2 || throw(ArgumentError("The first code must be a subcode of the second in construction X."))
    are_equivalent(C1, C2) && throw(ArgumentError("The first code must be a proper subcode of the second in construction X."))
    C1.F == C2.F == C3.F || throw(ArgumentError("All codes must be over the same base ring in construction X."))
    C2.k == C1.k + dimension(C3) || throw(ArgumentError("The dimension of the second code must be the sum of the dimensions of the first and third codes."))

    G1 = generator_matrix(C1)
    G3 = generator_matrix(C3)
    G_quotient = generator_matrix(C2 / C1)
    
    G_new = vcat(hcat(G_quotient, G3), hcat(G1, zero_matrix(C1.F, C1.k, C3.n)))
    C = LinearCode(G_new)
    
    C.n == C1.n + C3.n || error("Something went wrong in construction X. Expected length $(C1.n + C3.n) but obtained length $(C.n)")

    if !ismissing(C1.d) && !ismissing(C2.d) && !ismissing(C3.d)
        C.d = minimum([C1.d, C2.d + C3.d])
        C.l_bound = C.d
        C.u_bound = C.d
    elseif ismissing(C.d)
        set_distance_lower_bound!(C, min(C1.l_bound, C2.l_bound + C3.l_bound))
    end
    return C
end

"""
$(TYPEDSIGNATURES)

Return the code generated by the construction X3 procedure.
"""
function construction_X3(C1::AbstractLinearCode, C2::AbstractLinearCode, C3::AbstractLinearCode, C4::AbstractLinearCode, C5::AbstractLinearCode)
    C1 ⊆ C2 || throw(ArgumentError("The first code must be a subcode of the second in construction X3."))
    are_equivalent(C1, C2) && throw(ArgumentError("The first code must be a proper subcode of the second in construction X3."))
    C2 ⊆ C3 || throw(ArgumentError("The second code must be a subcode of the third in construction X3."))
    are_equivalent(C2, C3) && throw(ArgumentError("The second code must be a proper subcode of the third in construction X3."))
    C1.F == C4.F == C5.F || throw(ArgumentError("All codes must be over the same base ring in construction X3."))
    C3.k == C2.k + C4.k || throw(ArgumentError("The dimension of the third code must be the sum of the dimensions of the second and fourth codes in construction X3."))
    C2.k == C1.k + C5.k || throw(ArgumentError("The dimension of the second code must be the sum of the dimensions of the first and fifth codes in construction X3."))

    C2_mod_C1 = C2 / C1
    C3_mod_C2 = C3 / C2
    F = C1.F

    G1 = generator_matrix(C1)
    G4 = generator_matrix(C4)
    G5 = generator_matrix(C5)
    
    G = vcat(hcat(G1, zero_matrix(F, C1.k, C4.n), zero_matrix(F, C1.k, C5.n)),
             hcat(generator_matrix(C2_mod_C1), G4, zero_matrix(F, C4.k, C5.n)),
             hcat(generator_matrix(C3_mod_C2), zero_matrix(F, C5.k, C4.n), G5))
             
    C = LinearCode(G)
    
    if !ismissing(C1.d) && !ismissing(C2.d) && !ismissing(C3.d) && !ismissing(C4.d) && !ismissing(C5.d) && ismissing(C.d)
        set_distance_lower_bound!(C, minimum([C1.d, C2.d + C4.d, C3.d + C5.d]))
    end
    return C
end

# ==============================================================================
# COMPOSITE CODE LAZY GETTERS
# ==============================================================================

# function generator_matrix(C::PlotkinCode, stand_form::Bool = false)
#     cache = getfield(C, :cache)
#     if !haskey(cache, :G)
#         G1 = generator_matrix(C.C1)
#         G2 = generator_matrix(C.C2)
#         cache[:G] = vcat(hcat(G1, G1), hcat(zero_matrix(C.F, nrows(G2), ncols(G1)), G2))
#     end
#     if stand_form
#         if !haskey(cache, :G_stand)
#             G_stand, H_stand, P, _ = _standard_form(cache[:G])
#             cache[:G_stand] = G_stand
#             cache[:H_stand] = H_stand
#             cache[:P_stand] = P
#         end
#         return cache[:G_stand]
#     end
#     return cache[:G]
# end

# function parity_check_matrix(C::PlotkinCode, stand_form::Bool = false)
#     cache = getfield(C, :cache)
#     if !haskey(cache, :H)
#         H1 = parity_check_matrix(C.C1)
#         H2 = parity_check_matrix(C.C2)
#         cache[:H] = vcat(hcat(H1, zero_matrix(C.F, nrows(H1), ncols(H1))), hcat(-H2, H2))
#     end
#     if stand_form
#         # Forcing generator standard form inherently computes H_stand
#         generator_matrix(C, true) 
#         return cache[:H_stand]
#     end
#     return cache[:H]
# end

# function generator_matrix(C::DirectSumCode, stand_form::Bool = false)
#     cache = getfield(C, :cache)
#     if !haskey(cache, :G)
#         cache[:G] = direct_sum(generator_matrix(C.C1), generator_matrix(C.C2))
#     end
#     if stand_form
#         if !haskey(cache, :G_stand)
#             G_stand, H_stand, P, _ = _standard_form(cache[:G])
#             cache[:G_stand] = G_stand
#             cache[:H_stand] = H_stand
#             cache[:P_stand] = P
#         end
#         return cache[:G_stand]
#     end
#     return cache[:G]
# end

# function parity_check_matrix(C::DirectSumCode, stand_form::Bool = false)
#     cache = getfield(C, :cache)
#     if !haskey(cache, :H)
#         cache[:H] = direct_sum(parity_check_matrix(C.C1), parity_check_matrix(C.C2))
#     end
#     if stand_form
#         generator_matrix(C, true)
#         return cache[:H_stand]
#     end
#     return cache[:H]
# end

# function generator_matrix(C::TensorProductCode, stand_form::Bool = false)
#     cache = getfield(C, :cache)
#     if !haskey(cache, :G)
#         cache[:G] = generator_matrix(C.C1) ⊗ generator_matrix(C.C2)
#     end
#     if stand_form
#         if !haskey(cache, :G_stand)
#             G_stand, H_stand, P, _ = _standard_form(cache[:G])
#             cache[:G_stand] = G_stand
#             cache[:H_stand] = H_stand
#             cache[:P_stand] = P
#         end
#         return cache[:G_stand]
#     end
#     return cache[:G]
# end

# ==============================================================================
# SUM AND PRODUCT CONSTRUCTORS
# ==============================================================================

"""
$(TYPEDSIGNATURES)

Return the direct sum code of `C1` and `C2`. Evaluates lazily.
"""
function ⊕(C1::AbstractLinearCode, C2::AbstractLinearCode)
    C1.F == C2.F || throw(ArgumentError("Codes must be over the same field."))

    n_new = C1.n + C2.n
    k_new = C1.k + C2.k
    
    if !ismissing(C1.d) && !ismissing(C2.d)
        d_new = min(C1.d, C2.d)
        lb, ub = d_new, d_new
    else
        d_new = missing
        lb = min(C1.l_bound, C2.l_bound)
        ub = min(C1.u_bound, C2.u_bound)
    end
    
    cache = Dict{Symbol, Any}()
    return DirectSumCode(C1, C2, C1.F, n_new, k_new, d_new, lb, ub, cache)
end
direct_sum(C1::AbstractLinearCode, C2::AbstractLinearCode) = C1 ⊕ C2

"""
$(TYPEDSIGNATURES)

Return the (direct) product code of `C1` and `C2` (Tensor product of their generator matrices).
Evaluates lazily.
"""
function ×(C1::AbstractLinearCode, C2::AbstractLinearCode)
    C1.F == C2.F || throw(ArgumentError("Codes must be over the same field."))

    n_new = C1.n * C2.n
    k_new = C1.k * C2.k
    
    if !ismissing(C1.d) && !ismissing(C2.d)
        d_new = C1.d * C2.d
        lb, ub = d_new, d_new
    else
        d_new = missing
        lb = C1.l_bound * C2.l_bound
        ub = C1.u_bound * C2.u_bound
    end
    
    cache = Dict{Symbol, Any}()
    return TensorProductCode(C1, C2, C1.F, n_new, k_new, d_new, lb, ub, cache)
end
direct_product(C1::AbstractLinearCode, C2::AbstractLinearCode) = C1 × C2
product_code(C1::AbstractLinearCode, C2::AbstractLinearCode) = C1 × C2

"""
$(TYPEDSIGNATURES)
    
Return the tensor product code of `C1` and `C2` defined by the Kronecker product 
of their parity-check matrices.
"""
function ⊗(C1::AbstractLinearCode, C2::AbstractLinearCode)
    C1.F == C2.F || throw(ArgumentError("Codes must be over the same field."))
    
    H1 = parity_check_matrix(C1)
    H2 = parity_check_matrix(C2)
    H_new = H1 ⊗ H2
    
    n_new = C1.n * C2.n
    k_new = n_new - ((C1.n - C1.k) * (C2.n - C2.k))
    
    cache = Dict{Symbol, Any}(:H => H_new)
    # Reverting to the generic LinearCode since we are injecting H directly
    return LinearCode(C1.F, n_new, k_new, missing, 1, n_new, cache)
end
kron(C1::AbstractLinearCode, C2::AbstractLinearCode) = C1 ⊗ C2
tensor_product(C1::AbstractLinearCode, C2::AbstractLinearCode) = C1 ⊗ C2

"""
$(TYPEDSIGNATURES)

Return the entrywise (Schur) product of `C` and `D`.
"""
function entrywise_product_code(C::AbstractLinearCode, D::AbstractLinearCode)
    C.F == D.F || throw(ArgumentError("Codes must be over the same field in the Schur product."))
    C.n == D.n || throw(ArgumentError("Codes must have the same length in the Schur product."))

    G_C = generator_matrix(C)
    G_D = generator_matrix(D)
    nr_C = nrows(G_C)
    nr_D = nrows(G_D)
    F = C.F

    # BUG FIX: Massive optimization to avoid `reduce(vcat)` array allocation blowup.
    if C === D
        # Symmetric case: Only iterate upper triangle
        nr_new = div(nr_C * (nr_C + 1), 2)
        G_new = zero_matrix(F, nr_new, C.n)
        row_idx = 1
        for i in 1:nr_C
            for j in i:nr_C
                for col in 1:C.n
                    G_new[row_idx, col] = G_C[i, col] * G_C[j, col]
                end
                row_idx += 1
            end
        end
    else
        # Full cross-product case
        nr_new = nr_C * nr_D
        G_new = zero_matrix(F, nr_new, C.n)
        row_idx = 1
        for i in 1:nr_C
            for j in 1:nr_D
                for col in 1:C.n
                    G_new[row_idx, col] = G_C[i, col] * G_D[j, col]
                end
                row_idx += 1
            end
        end
    end
    
    # We must use the eager LinearCode constructor here because the actual dimension `k`
    # of a Schur product code is not guaranteed (can be anywhere from max(k1, k2) to n).
    return LinearCode(G_new)
end
*(C::AbstractLinearCode, D::AbstractLinearCode) = entrywise_product_code(C, D)
Schur_product_code(C::AbstractLinearCode, D::AbstractLinearCode) = entrywise_product_code(C, D)
Hadamard_product_code(C::AbstractLinearCode, D::AbstractLinearCode) = entrywise_product_code(C, D)
componentwise_product_code(C::AbstractLinearCode, D::AbstractLinearCode) = entrywise_product_code(C, D)

# ==============================================================================
# COMPOSITE CODE LAZY GETTERS
# ==============================================================================

function generator_matrix(C::PlotkinCode, stand_form::Bool = false)
    cache = getfield(C, :cache)
    if !haskey(cache, :G)
        G1 = generator_matrix(C.C1)
        G2 = generator_matrix(C.C2)
        cache[:G] = vcat(hcat(G1, G1), hcat(zero_matrix(C.F, nrows(G2), ncols(G1)), G2))
    end
    if stand_form
        if !haskey(cache, :G_stand)
            G_stand, H_stand, P, _ = _standard_form(cache[:G])
            cache[:G_stand] = G_stand
            cache[:H_stand] = H_stand
            cache[:P_stand] = P
        end
        return cache[:G_stand]
    end
    return cache[:G]
end

function parity_check_matrix(C::PlotkinCode, stand_form::Bool = false)
    cache = getfield(C, :cache)
    if !haskey(cache, :H)
        H1 = parity_check_matrix(C.C1)
        H2 = parity_check_matrix(C.C2)
        cache[:H] = vcat(hcat(H1, zero_matrix(C.F, nrows(H1), ncols(H1))), hcat(-H2, H2))
    end
    if stand_form
        # Forcing generator standard form inherently computes H_stand
        generator_matrix(C, true) 
        return cache[:H_stand]
    end
    return cache[:H]
end

function generator_matrix(C::DirectSumCode, stand_form::Bool = false)
    cache = getfield(C, :cache)
    if !haskey(cache, :G)
        cache[:G] = direct_sum(generator_matrix(C.C1), generator_matrix(C.C2))
    end
    if stand_form
        if !haskey(cache, :G_stand)
            G_stand, H_stand, P, _ = _standard_form(cache[:G])
            cache[:G_stand] = G_stand
            cache[:H_stand] = H_stand
            cache[:P_stand] = P
        end
        return cache[:G_stand]
    end
    return cache[:G]
end

function parity_check_matrix(C::DirectSumCode, stand_form::Bool = false)
    cache = getfield(C, :cache)
    if !haskey(cache, :H)
        cache[:H] = direct_sum(parity_check_matrix(C.C1), parity_check_matrix(C.C2))
    end
    if stand_form
        generator_matrix(C, true)
        return cache[:H_stand]
    end
    return cache[:H]
end

function generator_matrix(C::TensorProductCode, stand_form::Bool = false)
    cache = getfield(C, :cache)
    if !haskey(cache, :G)
        cache[:G] = generator_matrix(C.C1) ⊗ generator_matrix(C.C2)
    end
    if stand_form
        if !haskey(cache, :G_stand)
            G_stand, H_stand, P, _ = _standard_form(cache[:G])
            cache[:G_stand] = G_stand
            cache[:H_stand] = H_stand
            cache[:P_stand] = P
        end
        return cache[:G_stand]
    end
    return cache[:G]
end

# ==============================================================================
# SUM AND PRODUCT CONSTRUCTORS
# ==============================================================================

"""
$(TYPEDSIGNATURES)

Return the direct sum code of `C1` and `C2`. Evaluates lazily.
"""
function ⊕(C1::AbstractLinearCode, C2::AbstractLinearCode)
    C1.F == C2.F || throw(ArgumentError("Codes must be over the same field."))

    n_new = C1.n + C2.n
    k_new = C1.k + C2.k
    
    if !ismissing(C1.d) && !ismissing(C2.d)
        d_new = min(C1.d, C2.d)
        lb, ub = d_new, d_new
    else
        d_new = missing
        lb = min(C1.l_bound, C2.l_bound)
        ub = min(C1.u_bound, C2.u_bound)
    end
    
    cache = Dict{Symbol, Any}()
    return DirectSumCode(C1, C2, C1.F, n_new, k_new, d_new, lb, ub, cache)
end
direct_sum(C1::AbstractLinearCode, C2::AbstractLinearCode) = C1 ⊕ C2

"""
$(TYPEDSIGNATURES)

Return the (direct) product code of `C1` and `C2` (Tensor product of their generator matrices).
Evaluates lazily.
"""
function ×(C1::AbstractLinearCode, C2::AbstractLinearCode)
    C1.F == C2.F || throw(ArgumentError("Codes must be over the same field."))

    n_new = C1.n * C2.n
    k_new = C1.k * C2.k
    
    if !ismissing(C1.d) && !ismissing(C2.d)
        d_new = C1.d * C2.d
        lb, ub = d_new, d_new
    else
        d_new = missing
        lb = C1.l_bound * C2.l_bound
        ub = C1.u_bound * C2.u_bound
    end
    
    cache = Dict{Symbol, Any}()
    return TensorProductCode(C1, C2, C1.F, n_new, k_new, d_new, lb, ub, cache)
end
direct_product(C1::AbstractLinearCode, C2::AbstractLinearCode) = C1 × C2
product_code(C1::AbstractLinearCode, C2::AbstractLinearCode) = C1 × C2

"""
$(TYPEDSIGNATURES)
    
Return the tensor product code of `C1` and `C2` defined by the Kronecker product 
of their parity-check matrices.
"""
function ⊗(C1::AbstractLinearCode, C2::AbstractLinearCode)
    C1.F == C2.F || throw(ArgumentError("Codes must be over the same field."))
    
    H1 = parity_check_matrix(C1)
    H2 = parity_check_matrix(C2)
    H_new = H1 ⊗ H2
    
    n_new = C1.n * C2.n
    k_new = n_new - ((C1.n - C1.k) * (C2.n - C2.k))
    
    cache = Dict{Symbol, Any}(:H => H_new)
    # Reverting to the generic LinearCode since we are injecting H directly
    return LinearCode(C1.F, n_new, k_new, missing, 1, n_new, cache)
end
kron(C1::AbstractLinearCode, C2::AbstractLinearCode) = C1 ⊗ C2
tensor_product(C1::AbstractLinearCode, C2::AbstractLinearCode) = C1 ⊗ C2

"""
$(TYPEDSIGNATURES)

Return the entrywise (Schur) product of `C` and `D`.
"""
function entrywise_product_code(C::AbstractLinearCode, D::AbstractLinearCode)
    C.F == D.F || throw(ArgumentError("Codes must be over the same field in the Schur product."))
    C.n == D.n || throw(ArgumentError("Codes must have the same length in the Schur product."))

    G_C = generator_matrix(C)
    G_D = generator_matrix(D)
    nr_C = nrows(G_C)
    nr_D = nrows(G_D)
    F = C.F

    # BUG FIX: Massive optimization to avoid `reduce(vcat)` array allocation blowup.
    if C === D
        # Symmetric case: Only iterate upper triangle
        nr_new = div(nr_C * (nr_C + 1), 2)
        G_new = zero_matrix(F, nr_new, C.n)
        row_idx = 1
        for i in 1:nr_C
            for j in i:nr_C
                for col in 1:C.n
                    G_new[row_idx, col] = G_C[i, col] * G_C[j, col]
                end
                row_idx += 1
            end
        end
    else
        # Full cross-product case
        nr_new = nr_C * nr_D
        G_new = zero_matrix(F, nr_new, C.n)
        row_idx = 1
        for i in 1:nr_C
            for j in 1:nr_D
                for col in 1:C.n
                    G_new[row_idx, col] = G_C[i, col] * G_D[j, col]
                end
                row_idx += 1
            end
        end
    end
    
    # We must use the eager LinearCode constructor here because the actual dimension `k`
    # of a Schur product code is not guaranteed (can be anywhere from max(k1, k2) to n).
    return LinearCode(G_new)
end
*(C::AbstractLinearCode, D::AbstractLinearCode) = entrywise_product_code(C, D)
Schur_product_code(C::AbstractLinearCode, D::AbstractLinearCode) = entrywise_product_code(C, D)
Hadamard_product_code(C::AbstractLinearCode, D::AbstractLinearCode) = entrywise_product_code(C, D)
componentwise_product_code(C::AbstractLinearCode, D::AbstractLinearCode) = entrywise_product_code(C, D)

# ==============================================================================
# QUOTIENT CODES
# ==============================================================================

"""
$(TYPEDSIGNATURES)

Return the complementary subcode `C2 / C1` given `C1 ⊆ C2`.
"""
function /(C2::AbstractLinearCode, C1::AbstractLinearCode)
    C1.F == C2.F || throw(ArgumentError("Codes must be over the same field."))
    C1 ⊆ C2 || throw(ArgumentError("C1 is not a subcode of C2."))
    
    G1 = generator_matrix(C1)
    G2 = generator_matrix(C2)
    
    # Use the ultra-fast linear algebra quotient bypass
    Q = _quotient_space(G1, G2)
    
    # The resulting code is a subcode of C2, so its distance is bounded by C2's distance
    lb = ismissing(C2.d) ? C2.l_bound : C2.d
    cache = Dict{Symbol, Any}(:G => Q)
    
    return LinearCode(C1.F, C1.n, nrows(Q), missing, lb, C1.n, cache)
end
quo(C1::AbstractLinearCode, C2::AbstractLinearCode) = /(C1, C2)
quotient(C1::AbstractLinearCode, C2::AbstractLinearCode) = /(C1, C2)
code_complement(C2::AbstractLinearCode, C1::AbstractLinearCode) = /(C1, C2)

# ==============================================================================
# JUXTAPOSITION
# ==============================================================================

"""
$(TYPEDSIGNATURES)

Return the code generated by the horizontal concatenation of the generator
matrices of `C1` then `C2`.
"""
function juxtaposition(C1::AbstractLinearCode, C2::AbstractLinearCode)
    C1.F == C2.F || throw(ArgumentError("Cannot juxtapose two codes over different fields."))
    
    G1 = generator_matrix(C1)
    G2 = generator_matrix(C2)
    nrows(G1) == nrows(G2) || throw(ArgumentError("Cannot juxtapose codes with generator matrices with a different number of rows."))

    G_new = hcat(G1, G2)
    
    # A message x encoded via [G1 | G2] yields codeword [c1 | c2], so wt(c) = wt(c1) + wt(c2)
    d_lower = C1.l_bound + C2.l_bound
    d_upper = C1.u_bound + C2.u_bound
    d_new = (!ismissing(C1.d) && !ismissing(C2.d)) ? C1.d + C2.d : missing
    
    cache = Dict{Symbol, Any}(:G => G_new)
    return LinearCode(C1.F, C1.n + C2.n, C1.k, d_new, d_lower, d_upper, cache)
end

# ==============================================================================
# TRANSPOSE & PERMUTATIONS
# ==============================================================================

"""
$(TYPEDSIGNATURES)

Return the transposed code of `C`.
"""
function Base.transpose(C::AbstractLinearCode)
    # The transpose code treats the transposed parity check matrix as its new parity check matrix
    H_trans = transpose(parity_check_matrix(C))
    cache = Dict{Symbol, Any}(:H => H_trans)
    
    n_new = ncols(H_trans)
    k_new = n_new - nrows(H_trans)
    
    return LinearCode(C.F, n_new, k_new, missing, 1, n_new, cache)
end

"""
$(TYPEDSIGNATURES)

Return the code whose generator matrix is `C`'s with the columns permuted by `σ`.
"""
function permute_code(C::AbstractLinearCode, σ::Union{PermGroupElem, Perm{Int}, Vector{Int}})
    P = transpose(permutation_matrix(C.F, typeof(σ) <: Perm ? σ.d : σ))
    size(P, 1) == C.n || throw(ArgumentError("Incorrect number of digits in permutation."))
    
    # Permuting columns has exactly zero effect on minimum distance bounds!
    cache = Dict{Symbol, Any}()
    
    # Lazily pull and permute matrices only if they already exist
    old_cache = getfield(C, :cache)
    haskey(old_cache, :G) && (cache[:G] = old_cache[:G] * P)
    haskey(old_cache, :H) && (cache[:H] = old_cache[:H] * P)
    
    if haskey(old_cache, :P_stand)
        cache[:P_stand] = old_cache[:P_stand] * P
    end
    
    # We must construct a completely fresh object, as standard forms will differ entirely
    C_new = LinearCode(C.F, C.n, C.k, C.d, C.l_bound, C.u_bound, cache)
    
    # Handle Quasicyclic specifically if needed
    if isa(C, QuasiCyclicCode)
        @warn "Permuting a QuasiCyclicCode returns a standard LinearCode, as the quasi-cyclic structure is destroyed."
    end
    
    return C_new
end

"""
$(TYPEDSIGNATURES)

Return the extended code of `C` extending on column `c`. For each row
`g` of the generator matrix for `C`, a digit `-a ⋅ g` is inserted in
the `c`th position. If `c` isn't given, it is appended. If `a` isn't
given, then the all 1's vector is used giving an even extension.
"""
function extend(C::AbstractLinearCode, a::CTMatrixTypes, c::Integer)
    1 <= c <= C.n + 1 || throw(ArgumentError("The code has length $(C.n), so `c` must be between 1 and $(C.n + 1)."))
    length(a) == C.n || throw(ArgumentError("The vector `a` should have length $(C.n)."))
    b = ncols(a) == 1 ? transpose(a) : a
    nrows(b) == 1 || throw(ArgumentError("The argument `a` should be a vector."))

    F = field(C)
    G = generator_matrix(C)
    nr, nc = nrows(G), ncols(G)
    
    new_col = zero_matrix(F, nr, 1)
    is_binary = order(F) == 2
    
    # Calculate the new column based on the weighted sum definition
    for i in 1:nr
        val = F(0)
        for j in 1:nc
            val += b[1, j] * G[i, j]
        end
        new_col[i, 1] = is_binary ? val : -val
    end
    
    G_new = hcat(view(G, :, 1:c - 1), new_col, view(G, :, c:nc))
    cache = Dict{Symbol, Any}(:G => G_new)

    # Cache-Aware H Extension: Only compute H_new if H already exists
    old_cache = getfield(C, :cache)
    if haskey(old_cache, :H)
        H = old_cache[:H]
        new_row = hcat(view(b, 1:1, 1:c - 1), matrix(F, 1, 1, [1]), view(b, 1:1, c:nc))
        H_new = vcat(new_row, hcat(view(H, :, 1:c - 1), zero_matrix(F, nrows(H), 1), view(H, :, c:nc)))
        cache[:H] = H_new
    end

    # Distance bound updates
    d_new = missing
    l_new, u_new = 1, C.n + 1
    if !ismissing(C.d)
        if is_binary && all(isone(x) for x in b)
            d_new = iseven(C.d) ? C.d : C.d + 1
            l_new, u_new = d_new, d_new
        else
            l_new = C.d
            u_new = C.d + 1
        end
    else
        if is_binary && all(isone(x) for x in b)
            l_new = iseven(C.l_bound) ? C.l_bound : C.l_bound + 1
            u_new = iseven(C.u_bound) ? C.u_bound : C.u_bound + 1
        else
            l_new = C.l_bound
            u_new = C.u_bound + 1
        end
    end

    return LinearCode(F, nc + 1, C.k, d_new, l_new, u_new, cache)
end
extend(C::AbstractLinearCode, c::Integer) = extend(C, matrix(field(C), 1, C.n, ones(Int, C.n)), c)
extend(C::AbstractLinearCode, a::CTMatrixTypes) = extend(C, a, C.n + 1)
extend(C::AbstractLinearCode) = extend(C, matrix(field(C), 1, C.n, ones(Int, C.n)), C.n + 1)
even_extension(C::AbstractLinearCode) = extend(C)

"""
$(TYPEDSIGNATURES)

Return the code of `C` punctured at the columns in `cols`.
"""
function puncture(C::AbstractLinearCode, cols::Vector{<:Integer})
    isempty(cols) && return C
    allunique(cols) || throw(ArgumentError("Columns to puncture are not unique."))
    cols ⊆ 1:C.n || throw(ArgumentError("Columns to puncture are not a subset of the index set."))
    length(cols) == C.n && throw(ArgumentError("Cannot puncture all columns of a generator matrix."))

    G = generator_matrix(C)[:, setdiff(1:C.n, cols)]
    G = _remove_empty(G, :rows)
    
    # We must use the eager constructor because puncturing can drop the rank
    C_new = LinearCode(G)
    
    # Inject lower bound safely
    set_distance_lower_bound!(C_new, max(1, C.l_bound - length(cols)))
    return C_new
end
puncture(C::AbstractLinearCode, cols::Integer) = puncture(C, [cols])

"""
$(TYPEDSIGNATURES)

Return the code of `C` expurgated at the rows in `rows`.
"""
function expurgate(C::AbstractLinearCode, rows::Vector{<:Integer})
    isempty(rows) && return C
    allunique(rows) || throw(ArgumentError("Rows to expurgate are not unique."))
    
    G = generator_matrix(C)
    nr = nrows(G)
    rows ⊆ 1:nr || throw(ArgumentError("Rows to expurgate are not a subset of the index set."))
    length(rows) == nr && throw(ArgumentError("Cannot expurgate all rows of a generator matrix."))

    G_new = G[setdiff(1:nr, rows), :]
    
    C_new = LinearCode(G_new)
    set_distance_lower_bound!(C_new, C.l_bound)
    return C_new
end
expurgate(C::AbstractLinearCode, rows::Integer) = expurgate(C, [rows])

"""
$(TYPEDSIGNATURES)

Return the code of `C` shortened on the indices `L`.
"""
shorten(C::AbstractLinearCode, L::Vector{<:Integer}) = isempty(L) ? C : dual(puncture(dual(C), L))
shorten(C::AbstractLinearCode, L::Integer) = shorten(C, [L])

"""
$(TYPEDSIGNATURES)

Return the code of `C` whose generator matrix is augmented with `M`.
"""
function augment(C::AbstractLinearCode, M::CTMatrixTypes)
    iszero(M) && throw(ArgumentError("Zero matrix passed to augment."))
    C.n == ncols(M) || throw(ArgumentError("Rows to augment must have the same number of columns as the generator matrix."))
    C.F == base_ring(M) || throw(ArgumentError("Rows to augment must have the same base field as the code."))

    M = _remove_empty(M, :rows)
    G = vcat(generator_matrix(C), M)
    
    C_new = LinearCode(G)
    return C_new
end
augment(C::AbstractLinearCode, M::Matrix{<:Integer}) = augment(C, matrix(field(C), M))

"""
$(TYPEDSIGNATURES)

Return the lengthened code of `C`.
"""
lengthen(C::AbstractLinearCode) = extend(augment(C, matrix(field(C), ones(Int, 1, C.n))))

"""
$(TYPEDSIGNATURES)

Return a `k`-dimensional subcode of `C`.
"""
function subcode(C::AbstractLinearCode, k::Int)
    k >= 1 && k < C.k || throw(ArgumentError("Cannot construct a $k-dimensional subcode of an $(C.k)-dimensional code."))
    k == C.k && return C
    
    P = standard_form_permutation(C)
    G = ismissing(P) ? view(generator_matrix(C, true), 1:k, :) : view(generator_matrix(C, true), 1:k, :) * P
    
    # We must use eager construction because slicing removes the distance bounds
    return LinearCode(G)
end

"""
$(TYPEDSIGNATURES)

Return a subcode of `C` using the rows of the generator matrix of `C` listed in `rows`.
"""
function subcode(C::AbstractLinearCode, rows::Vector{Int})
    isempty(rows) && throw(ArgumentError("Row index set empty in subcode."))
    allunique(rows) || throw(ArgumentError("Rows are not unique."))
    rows ⊆ 1:C.k || throw(ArgumentError("Rows are not a subset of the index set."))
    length(rows) == C.k && return C
    
    G = generator_matrix(C)[setdiff(1:C.k, rows), :]
    return LinearCode(G)
end

"""
$(TYPEDSIGNATURES)

Return a subcode of dimension `k` between `C1` and `C2`.
"""
function subcode_of_dimension_between_codes(C1::AbstractLinearCode, C2::AbstractLinearCode, k::Int)
    C2 ⊆ C1 || throw(ArgumentError("C2 must be a subcode of C1"))
    C2.k <= k <= C1.k || throw(ArgumentError("The dimension must be between that of C1 and C2."))
    
    k == C2.k && return C2
    k == C1.k && return C1
    
    C = C1 / C2
    P = standard_form_permutation(C)
    
    G_sub = ismissing(P) ? generator_matrix(C, true)[1:(k - C2.k), :] : generator_matrix(C, true)[1:(k - C2.k), :] * P
    return augment(C2, G_sub)
end

"""
$(TYPEDSIGNATURES)

Return the expanded code of `C` constructed by expanding the generator matrix
to the subfield `K` using the basis `β` for `field(C)` over `K`.
"""
function expanded_code(C::AbstractLinearCode, K::CTFieldTypes, β::Vector{<:CTFieldElem})
    flag, _ = is_basis(C.F, K, β)
    flag || throw(ArgumentError("β is not a basis for the extension"))

    G = generator_matrix(C)
    G_new = zero_matrix(C.F, nrows(G) * length(β), ncols(G))
    
    curr_row = 1
    for r in 1:nrows(G)
        for βi in β
            G_new[curr_row, :] = βi * view(G, r:r, :)
            curr_row += 1
        end
    end
    
    # Expand the matrix over the subfield K
    G_exp = expand_matrix(G_new, K, β)

    C_new = LinearCode(G_exp)
    set_distance_lower_bound!(C_new, C.l_bound)
    return C_new
end

"""
$(TYPEDSIGNATURES)

Return the subfield subcode code of `C` over `K` using the provided dual `basis`
for the field of `C` over `K`.
"""
function subfield_subcode(C::AbstractLinearCode, K::CTFieldTypes, basis::Vector{<:CTFieldElem})
    H_exp = transpose(expand_matrix(transpose(parity_check_matrix(C)), K, basis))
    
    # Passing `true` creates the code treating H_exp as the parity check matrix
    C_new = LinearCode(H_exp, true)
    return C_new
end

"""
$(TYPEDSIGNATURES)

Return the trace code of `C` over `K` using the provided dual `basis`
for the field of `C` over `K` using Delsarte's theorem.
"""
trace_code(C::AbstractLinearCode, K::CTFieldTypes, basis::Vector{<:CTFieldElem}) = dual(subfield_subcode(dual(C), K, basis))

"""
$(TYPEDSIGNATURES)

Return the even subcode of `C`.
"""
function even_subcode(C::AbstractLinearCode)
    Int(order(C.F)) == 2 || throw(ArgumentError("Even-ness is only defined for binary codes."))

    # The even subcode is the intersection of C with the global even-parity code.
    # We can find this instantly by appending the all-ones vector to the parity check matrix.
    H = parity_check_matrix(C)
    ones_row = matrix(C.F, 1, C.n, ones(Int, C.n))
    
    H_new = vcat(H, ones_row)
    
    # Eagerly compute the code to establish the new basis.
    # Passing `true` tells the constructor to treat H_new as the parity-check matrix.
    C_even = LinearCode(H_new, true)
    
    # If the dimension collapses to 0, there is no even subcode
    C_even.k == 0 && return missing 
    return C_even
end

"""
$(TYPEDSIGNATURES)

Return the doubly-even subcode of `C`.
"""
function doubly_even_subcode(C::AbstractLinearCode)
    Int(order(C.F)) == 2 || throw(ArgumentError("Even-ness is only defined for binary codes."))

    # 1. Restrict to the even subcode
    C_even = even_subcode(C)
    ismissing(C_even) && return missing

    # 2. Control the overlap
    # The requirement wt(x ∩ y) == 0 mod 2 means the code must be self-orthogonal.
    # The largest self-orthogonal subcode of C_even is exactly its Euclidean hull.
    C_hull, hull_dim = hull(C_even)
    hull_dim == 0 && return missing

    # 3. Apply the weight four condition
    # Because we are on the hull, the map x -> wt(x)/2 mod 2 is now a strictly 
    # linear functional over GF(2). We just need its kernel.
    G_hull = generator_matrix(C_hull)
    F = C.F
    nr = nrows(G_hull)

    # Evaluate the linear functional on the basis vectors
    func_vals = [F(div(wt(view(G_hull, i:i, :)), 2) % 2) for i in 1:nr]

    # If all basis vectors are already 0 mod 4, the hull IS the doubly even subcode!
    all(iszero, func_vals) && return C_hull

    # Otherwise, the doubly even subcode has dimension k - 1. 
    # We sweep the basis to eliminate the odd functional values.
    G_doubly = zero_matrix(F, nr - 1, C.n)
    
    pivot_idx = findfirst(!iszero, func_vals)
    row_idx = 1
    for i in 1:nr
        i == pivot_idx && continue
        
        if iszero(func_vals[i])
            for c in 1:C.n
                G_doubly[row_idx, c] = G_hull[i, c]
            end
        else
            # Add the pivot vector to cancel out the 1 mod 4 condition
            for c in 1:C.n
                G_doubly[row_idx, c] = G_hull[i, c] + G_hull[pivot_idx, c]
            end
        end
        row_idx += 1
    end

    return LinearCode(G_doubly)
end

"""
$(TYPEDSIGNATURES)

Return a maximal triply-even subcode of `C`. 
Because the triply-even condition defines a cubic form over GF(2), the maximal 
subcode is not strictly unique. This returns the first maximal subspace found.
"""
function triply_even_subcode(C::AbstractLinearCode)
    Int(order(C.F)) == 2 || throw(ArgumentError("Even-ness is only defined for binary codes."))

    # 1. We must start inside the doubly even subcode
    C_DE = doubly_even_subcode(C)
    ismissing(C_DE) && return missing
    
    k = C_DE.k
    k == 0 && return missing
    n = C_DE.n
    
    G_DE = _Flint_matrix_to_Julia_int_matrix(generator_matrix(C_DE))
    
    # 2. Extract coefficients for the cubic form P(x) = 0 mod 2
    c_1 = zeros(Int, k)
    c_2 = zeros(Int, k, k)
    c_3 = zeros(Int, k, k, k)
    
    for i in 1:k
        w = wt(view(G_DE, i:i, :))
        c_1[i] = div(w, 4) % 2
        for j in (i + 1):k
            w_ij = wt(view(G_DE, i:i, :) .* view(G_DE, j:j, :))
            c_2[i, j] = div(w_ij, 2) % 2
            for l in (j + 1):k
                w_ijl = wt(view(G_DE, i:i, :) .* view(G_DE, j:j, :) .* view(G_DE, l:l, :))
                c_3[i, j, l] = w_ijl % 2
            end
        end
    end

    # 3. Fast evaluation of the cubic form for all 2^k vectors
    valid_vectors = Int[]
    for x_int in 1:(2^k - 1)
        x = digits(x_int, base=2, pad=k)
        
        # Evaluate P(x) mod 2
        val = 0
        for i in 1:k
            if x[i] == 1
                val ⊻= c_1[i]
                for j in (i + 1):k
                    if x[j] == 1
                        val ⊻= c_2[i, j]
                        for l in (j + 1):k
                            if x[l] == 1
                                val ⊻= c_3[i, j, l]
                            end
                        end
                    end
                end
            end
        end
        
        if val == 0
            push!(valid_vectors, x_int)
        end
    end
    
    isempty(valid_vectors) && return missing

    # 4. Extract a maximal linear subspace from the valid vectors
    # We use a greedy basis-building algorithm. Since it's a vector space, 
    # we just need to find a set of basis vectors whose ENTIRE SPAN is inside valid_vectors.
    valid_set = BitSet(valid_vectors)
    push!(valid_set, 0) # The zero vector is always valid
    
    best_basis = Int[]
    
    # Simple greedy search for the maximal basis
    for v in valid_vectors
        current_basis = [v]
        current_span = [0, v]
        
        for w in valid_vectors
            # Check if adding w keeps the entire new span inside the valid set
            w in current_span && continue
            
            new_elements = [w ⊻ s for s in current_span]
            if all(in.(new_elements, Ref(valid_set)))
                push!(current_basis, w)
                append!(current_span, new_elements)
            end
        end
        
        if length(current_basis) > length(best_basis)
            best_basis = current_basis
        end
    end
    
    isempty(best_basis) && return missing
    
    # 5. Translate the maximal integer basis back into a GF(2) generator matrix
    F = C.F
    dim_TE = length(best_basis)
    G_TE = zero_matrix(F, dim_TE, n)
    
    for i in 1:dim_TE
        x = digits(best_basis[i], base=2, pad=k)
        # Reconstruct the vector in GF(2)^n
        for col in 1:n
            val = 0
            for j in 1:k
                if x[j] == 1 && G_DE[j, col] == 1
                    val ⊻= 1
                end
            end
            G_TE[i, col] = F(val)
        end
    end
    
    return LinearCode(G_TE)
end

# """
# $(TYPEDSIGNATURES)

# Return the even subcode of `C`.
# """
# function even_subcode(C::AbstractLinearCode)
#     F = C.F
#     Int(order(F)) == 2 || throw(ArgumentError("Even-ness is only defined for binary codes."))

#     V_C, ψ = vector_space(C)
#     G_F_VS = AbstractAlgebra.vector_space(F, 1)
    
#     homo1_quad = ModuleHomomorphism(V_C, G_F_VS, matrix(F, dim(V_C), 1,
#         reduce(vcat, [F(wt(ψ(g).v) % 2) for g in gens(V_C)])))
        
#     even_sub, ϕ1 = kernel(homo1_quad)
    
#     iszero(dim(even_sub)) && return missing 
#     return LinearCode(reduce(vcat, [ψ(ϕ1(g)).v for g in gens(even_sub)]))
# end

# """
# $(TYPEDSIGNATURES)

# Return the doubly-even subcode of `C`.
# """
# function doubly_even_subcode(C::AbstractLinearCode)
#     F = C.F
#     Int(order(C.F)) == 2 || throw(ArgumentError("Even-ness is only defined for binary codes."))

#     V_C, ψ = vector_space(C)
#     G_F_VS = AbstractAlgebra.vector_space(F, 1)

#     # 1. Get the even subspace
#     homo1_quad = ModuleHomomorphism(V_C, G_F_VS, matrix(F, dim(V_C), 1,
#         reduce(vcat, [F(wt(ψ(g).v) % 2) for g in gens(V_C)])))
#     even_sub, ϕ1 = kernel(homo1_quad)

#     if !iszero(dim(even_sub))
#         # 2. Control the overlap (Ward's divisibility theorem)
#         homo2_bi = ModuleHomomorphism(even_sub, even_sub, matrix(F, dim(even_sub), dim(even_sub),
#             reduce(vcat, [F(wt(matrix(F, 1, C.n, ψ(ϕ1(gens(even_sub)[i])).v .*
#                 ψ(ϕ1(gens(even_sub)[j])).v)) % 2)
#             for i in 1:dim(even_sub), j in 1:dim(even_sub)])))
            
#         even_sub_w_overlap, μ1 = kernel(homo2_bi)

#         if !iszero(dim(even_sub_w_overlap))
#             # 3. Apply the weight four condition
#             homo2_quad = ModuleHomomorphism(even_sub_w_overlap, G_F_VS, matrix(F, dim(even_sub_w_overlap), 1, 
#                 reduce(vcat, [F(div(wt(ψ(ϕ1(μ1(g))).v), 2) % 2) for g in gens(even_sub_w_overlap)])))
                
#             four_sub, ϕ2 = kernel(homo2_quad)

#             if !iszero(dim(four_sub))
#                 return LinearCode(reduce(vcat, [ψ(ϕ1(μ1(ϕ2(g)))).v for g in gens(four_sub)]))
#             end
#         end
#     end
#     return missing
# end
