# Copyright (c) 2022 - 2026 Eric Sabo
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

#############################
        # constructors
#############################

function generator_matrix(C::QuasiCyclicCode, stand_form::Bool = false)
    cache = getfield(C, :cache)
    if C.A_type == :G && !haskey(cache, :G)
        cache[:G] = lift(C.A)
    elseif C.A_type == :H && !haskey(cache, :G)
        # If A specifies H, we must compute G via the kernel of the lifted H
        H_lift = parity_check_matrix(C)
        _, G = right_kernel(H_lift)
        cache[:G] = transpose(G)
    end
    
    if stand_form
        if !haskey(cache, :G_stand)
            G_stand, H_stand, P, _ = _standard_form(cache[:G])
            cache[:G_stand] = G_stand
            cache[:H_stand] = H_stand
            cache[:P_stand] = P
        end
        return cache[:G_stand]
    end
    return cache[:G]
end

function parity_check_matrix(C::QuasiCyclicCode, stand_form::Bool = false)
    cache = getfield(C, :cache)
    if C.A_type == :H && !haskey(cache, :H)
        cache[:H] = lift(C.A)
    elseif C.A_type == :G && !haskey(cache, :H)
        # If A specifies G, we must compute H via the kernel of the lifted G
        G_lift = generator_matrix(C)
        _, H = right_kernel(G_lift)
        cache[:H] = transpose(H)
    end
    
    if stand_form
        generator_matrix(C, true)
        return cache[:H_stand]
    end
    return cache[:H]
end

"""
$(TYPEDSIGNATURES)

Return the quasi-cyclic code specified by the matrix `A` of polynomial circulant generators. 
Evaluates lazily.
"""
function QuasiCyclicCode(A::MatElem{T}, parity::Bool=false) where T <: ResElem
    R = parent(A[1, 1])
    S = base_ring(R)
    F = base_ring(S)
    g = modulus(R)
    m = degree(g)
    g == gen(S)^m - 1 || throw(ArgumentError("Residue ring not of the form x^m - 1."))
    
    l = ncols(A)
    nr = nrows(A)
    n_full = l * m
    
    # We must determine k eagerly for the abstract type interface, but we only 
    # compute the rank of the lifted matrix, bypassing full nullspace extraction.
    A_lift = lift(A)
    rnk = rank(A_lift)
    
    k = parity ? (n_full - rnk) : rnk
    A_type = parity ? :H : :G
    
    cache = Dict{Symbol, Any}()
    return QuasiCyclicCode(F, R, n_full, k, missing, 1, n_full, l, m, A, A_type, cache)
end

"""
    QuasiCyclicCode(v::Vector{fqPolyRepMatrix}, l::Int, circ_gens::Bool, parity::Bool=false)

Return the quasi-cyclic code of index `l` generated by right-bit shifts of size `l` of the
generator vectors `v`. If `circ_gens` is `true`, the vectors are taken to be (column) generators
for the circulant matrices instead of generator vectors for the code. If the optional paramater
`parity` is set to `true`, the input is used to construct the parity-check matrix.

# Notes
* If `circ_gens` is `false`, then the length of the code is `ncols(v[1])` and must be divisible by `l`.
* If `circ_gens` is `true`, then the length of the code is `ncols(v[1]) * l`. Circulant matrices are
  stacked in rows of length `l`, so `l` must divide `length(v)`.
"""
function QuasiCyclicCode(v::Vector{T}, l::Int, circ_gens::Bool, parity::Bool=false) where T <: CTMatrixTypes
    F = base_ring(v[1])
    len_v = length(v)
    if circ_gens
        len_v >= 2 || throw(ArgumentError("Length of input vector must be at least two."))
        len_v % l == 0 || throw(ArgumentError("The length of the input vector must be divisible by l."))
        nr = div(len_v, l)
        r, m = size(v[1])
        (r != 1 && m != 1) && throw(ArgumentError("The input matrices must be vectors."))
        m == 1 && (v[1] = transpose(v[1]); (r, m = size(v[1]));)
        for i in 2:len_v
            F == base_ring(v[i]) || throw(ArgumentError("All inputs must be over the same base ring."))
            r2, m2 = size(v[i])
            (r2 != 1 && m2 != 1) && throw(ArgumentError("The input matrices must be vectors."))
            m2 == 1 && (v[i] = transpose(v[i]); (r2, m2 = size(v[i]));)
            m == m2 || throw(ArgumentError("The input vectors must all be the same length."))
        end

        S, x = polynomial_ring(F, :x)
        R, _ = residue_ring(S, x^m - 1)
        A = zero_matrix(R, nr, l)
        for r in 1:nr
            for c in 1:l
                temp = [v[(r - 1) * l + c][i] for i in 1:m]
                A[r, c] = R(S(temp))
            end
        end
        return QuasiCyclicCode(A, parity)
    else
        r, n = size(v[1])
        (r != 1 && n != 1) && throw(ArgumentError("The input matrices must be vectors."))
        n == 1 && (v[1] = transpose(v[1]); (r, n = size(v[1]));)
        n % l == 0 || throw(ArgumentError("Parameter l must divide the length of the vector."))
        m = div(n, l)
        for i in 2:len_v
            F == base_ring(v[i]) || throw(ArgumentError("All vectors must be over the same base ring."))
            r2, n2 = size(v[i])
            (r2 != 1 && n2 != 1) && throw(ArgumentError("The input matrices must be vectors."))
            n2 == 1 && (v[i] = transpose(v[i]); (r2, n2 = size(v[i]));)
            n == n2 || throw(ArgumentError("The input vectors must all be the same length."))
        end
        
        S, x = polynomial_ring(F, :x)
        R, _ = residue_ring(S, x^m - 1)
        A = zero_matrix(R, len_v, l)
        for k in 1:len_v
            for i in 1:l
                row = v[k]
                top_circ_row = zero_matrix(F, m, 1)
                for j in 1:m
                    top_circ_row[j, 1] = row[i + (j - 1) * l]
                end
                # transpose to get first circulant column
                top_circ_row[2:end, :] = top_circ_row[end:-1:2, :]
                A[k, i] = R(S([top_circ_row[i, 1] for i in 1:m]))
            end
        end
        return QuasiCyclicCode(A, parity)
    end
end

"""
    QuasiCyclicCode(v::fqPolyRepMatrix, l::Int, parity::Bool=false)

Return the quasi-cyclic code of index `l` generated by right-bit shifts of size `l` of the
generator vector `v`. If the optional paramater `parity` is set to `true`, the input is used
to construct the parity check matrix.
"""
QuasiCyclicCode(v::CTMatrixTypes, l::Int, parity::Bool=false) = QuasiCyclicCode([v], l, false, parity)

"""
    QuasiCyclicCode(v::Vector{fqPolyRepPolyRingElem}, n::Int, l::Int, parity::Bool=false)

Return the quasi-cyclic code of index `l` whose circulants are defined by the generator
polynomials `v`. If the optional paramater `parity` is set to `true`, the input is used
to construct the parity check matrix.
"""
function QuasiCyclicCode(v::Vector{T}, n::Int, l::Int, parity::Bool=false) where T <: CTMatrixTypes
    # if g = x^10 + α^2*x^9 + x^8 + α*x^7 + x^3 + α^2*x^2 + x + α
    # g.coeffs = [α  1  α^2  1  0  0  0  α  1  α^2  1]
    gen_vecs = Vector{T}()
    F = base_ring(v[1])
    for g in v
        temp = zero_matrix(F, 1, n)
        coeffs = collect(coefficients(g))
        temp[1, 1:length(coeffs)] = coeffs
        push!(gen_vecs, temp)
    end
    return QuasiCyclicCode(gen_vecs, l, true, parity)
end

"""
    QuasiCyclicCode(v::Vector{AbstractCyclicCode}, l::Int, parity::Bool=false)

Return the quasi-cyclic code of index `l` whose circulants are determined by the cyclic
codes in `v`. If the optional paramater `parity` is set to `true`, the input is used to
construct the parity check matrix.
"""
function QuasiCyclicCode(v::Vector{AbstractCyclicCode}, l::Int, parity::Bool=false)
    gen_vecs = Vector{fqPolyRepMatrix}()
    for C in v
        push!(gen_vecs, C.G[1, :])
    end
    return QuasiCyclicCode(gen_vecs, l, true, parity)
end

#############################
      # getter functions
#############################

"""
    index(C::AbstractQuasiCyclicCode)

Return the index of the quasi-cyclic code.
"""
index(C::AbstractQuasiCyclicCode) = C.l

"""
    expansion_factor(C::AbstractQuasiCyclicCode)

Return the expansion factor of the quasi-cycle code `C`.
"""
expansion_factor(C::AbstractQuasiCyclicCode) = C.m

"""
    type(C::AbstractQuasiCyclicCode)

Return the type of the quasi-cycle code `C`.
"""
type(C::AbstractQuasiCyclicCode) = C.type

"""
    polynomial_matrix(C::AbstractQuasiCyclicCode)

Return the polynomial matrix used to define the code.

Use `polynomial_matrix_type` to determine if specifies the generator or parity-check matrix.
"""
polynomial_matrix(C::AbstractQuasiCyclicCode) = C.A

"""
    polynomial_matrix_type(C::AbstractQuasiCyclicCode)

Return `'G'` if the polynomial matrix of `C` specifies the generator or parity-check matrix.
"""
polynomial_matrix_type(C::AbstractQuasiCyclicCode) = C.A_type

"""
    is_single_generator(C::AbstractQuasiCyclicCode)

Return `true` if `C` is a single-generator quasi-cyclic code.
"""
is_single_generator(C::AbstractQuasiCyclicCode) = (nrows(C.A) == 1;)

#############################
      # setter functions
#############################

#############################
     # general functions
#############################

"""
    base_matrix(A::MatElem{T}) where T <: ResElem
    protograph_matrix(A::MatElem{T}) where T <: ResElem
    weight_matrix(A::MatElem{T}) where T <: ResElem

Return the base/protograph/weight matrix of `A`.
"""
function weight_matrix(A::MatElem{T}) where T <: ResElem
    nr, nc = size(A)
    W = zeros(Int, nr, nc)
    for c in 1:nc
        for r in 1:nr
            W[r, c] = wt(Nemo.lift(A[r, c]))
        end
    end
    return W
end
base_matrix(A::MatElem{T}) where T <: ResElem = weight_matrix(A)
protograph_matrix(A::MatElem{T}) where T <: ResElem = weight_matrix(A)

"""
    noncirculant_generator_matrix(C::AbstractQuasiCyclicCode)

Return the non-circulant form of the generator matrix for the quasi-cyclic code `C` if the
polynomial matrix specifies the generator matrix; otherwise, return `missing`.
"""
function noncirculant_generator_matrix(C::AbstractQuasiCyclicCode)
    if C.A_type == :G
        flag = true
        for r in 1:C.m
            G_inner = zero_matrix(C.F, C.l, C.l * C.n)
            for col in 1:C.l
                C = lift(C.A[r, col])
                G_inner = zero(C)
                for i in 1:m
                    c = k % l
                    c == 0 && (c = l;)
                    G_inner[:, (i - 1) * l + c] = C[:, i]
                end
            end
            flag ? (G = G_inner;) : (G = vcat(G, G_inner);)
        end
        return G
    else
        return missing
    end
end

"""
    noncirculant_parity_check_matrix(C::AbstractQuasiCyclicCode)

Return the non-circulant form of the parity-check matrix for the quasi-cyclic code `C`
if the polynomial matrix specifies the parity-check matrix; otherwise, return `missing`.
"""
function noncirculant_parity_check_matrix(C::AbstractQuasiCyclicCode)
    if C.A_type == :H
        flag = true
        for r in 1:C.m
            H_inner = zero_matrix(C.F, C.l, C.l * C.n)
            for col in 1:C.l
                C = lift(C.A[r, col])
                H_inner = zero(C)
                for i in 1:m
                    c = k % l
                    c == 0 && (c = l;)
                    H_inner[:, (i - 1) * l + c] = C[:, i]
                end
            end
            flag ? (H = H_inner;) : (H = vcat(H, H_inner);)
        end
        return H
    else
        return missing
    end
end

"""
    generators(C::AbstractQuasiCyclicCode)

Return the generators of the quasi-cyclic code.
"""
function generators(C::AbstractQuasiCyclicCode)
    G = noncirculant_generator_matrix(C)
    gen_vecs = Vector{fqPolyRepMatrix}()
    nr = nrows(G)
    for i in 1:nr
        if i % l == 1
            push!(gen_vecs, G[i, :])
        end
    end
    return gen_vecs
end

"""
    circulants(C::AbstractQuasiCyclicCode)

Return the circulant matrices of the quasi-cyclic code.
"""
function circulants(C::AbstractQuasiCyclicCode)
    circulants = Vector{fqPolyRepMatrix}()
    nr, nc = size(C.A)
    # want stored in row order
    for r in 1:nr
        for c in 1:nc
            push!(circulants, lift(C.A[r, c]))
        end
    end
    return circulants
end

"""
$(TYPEDSIGNATURES)

Return the integer shift matrix (exponent matrix) of the Quasi-Cyclic code.

# Notes
* If a circulant is a pure monomial `x^e`, its entry is `e`.
* If a circulant is the zero matrix, its entry is `-1`.
* Throws an error if the matrix contains polynomials with multiple terms.
"""
function shift_matrix(C::AbstractQuasiCyclicCode)
    nr, nc = size(C.A)
    E = fill(-1, nr, nc)
    
    for r in 1:nr
        for c in 1:nc
            poly = lift(C.A[r, c])
            iszero(poly) && continue
            
            coeffs = collect(coefficients(poly))
            count(!iszero, coeffs) == 1 || throw(ArgumentError("Circulant at ($r, $c) is not a simple shift (has multiple terms)."))
            
            # Find the degree of the single non-zero term
            E[r, c] = findfirst(!iszero, coeffs) - 1
        end
    end
    
    return E
end
exponent_matrix(C::AbstractQuasiCyclicCode) = shift_matrix(C)

"""
$(TYPEDSIGNATURES)

Return `true` if the quasi-cyclic code contains an algebraic 4-cycle, based on 
Fossorier's condition. Evaluates entirely in the polynomial domain.
"""
function has_algebraic_4_cycle(C::AbstractQuasiCyclicCode)
    E = shift_matrix(C)
    nr, nc = size(E)
    m = C.m
    
    # A 4-cycle exists if there is a 2x2 submatrix in the shift matrix
    # without any -1 (null) entries, such that the alternating sum of shifts is 0 mod m.
    for r1 in 1:(nr - 1)
        for r2 in (r1 + 1):nr
            for c1 in 1:(nc - 1)
                for c2 in (c1 + 1):nc
                    e11, e12 = E[r1, c1], E[r1, c2]
                    e21, e22 = E[r2, c1], E[r2, c2]
                    
                    if e11 != -1 && e12 != -1 && e21 != -1 && e22 != -1
                        # Fossorier Condition for 2κ = 4
                        if mod(e11 - e12 + e22 - e21, m) == 0
                            return true
                        end
                    end
                end
            end
        end
    end
    return false
end

"""
$(TYPEDSIGNATURES)

Return `true` if the quasi-cyclic code contains an algebraic cycle of exactly `target_length`, 
based on Fossorier's condition.

# Notes
* `target_length` must be an even integer `2j` (e.g., 4, 6, 8).
* Evaluates entirely in the polynomial domain using a DFS backtracking algorithm.
"""
function has_algebraic_cycle(C::AbstractQuasiCyclicCode, target_length::Int)
    iseven(target_length) && target_length >= 4 || throw(ArgumentError("Target length must be an even integer >= 4."))
    
    E = shift_matrix(C) # Assuming exponent_matrix/shift_matrix alias is set
    nr, nc = size(E)
    m = C.m
    
    visited_rows = falses(nr)
    visited_cols = falses(nc)
    
    # Internal DFS closure
    function dfs(curr_node::Int, start_row::Int, depth::Int, current_sum::Int, is_row::Bool)
        # Base Case: Reached the target cycle length
        if depth == target_length
            return curr_node == start_row && mod(current_sum, m) == 0
        end
        
        if is_row
            r = curr_node
            visited_rows[r] = true
            
            for c in 1:nc
                if E[r, c] != -1 && !visited_cols[c]
                    # Going from Row -> Col: Add the shift exponent
                    if dfs(c, start_row, depth + 1, current_sum + E[r, c], false)
                        visited_rows[r] = false # Backtrack
                        return true
                    end
                end
            end
            visited_rows[r] = false # Backtrack
            
        else
            c = curr_node
            visited_cols[c] = true
            
            for r in 1:nr
                if E[r, c] != -1
                    # If we are exactly one step away from closing the loop, 
                    # we must strictly return to the start_row.
                    if depth == target_length - 1
                        if r == start_row
                            # Going from Col -> Row: Subtract the shift exponent
                            if dfs(r, start_row, depth + 1, current_sum - E[r, c], true)
                                visited_cols[c] = false # Backtrack
                                return true
                            end
                        end
                    else
                        # Otherwise, continue exploring unvisited rows
                        if !visited_rows[r]
                            if dfs(r, start_row, depth + 1, current_sum - E[r, c], true)
                                visited_cols[c] = false # Backtrack
                                return true
                            end
                        end
                    end
                end
            end
            visited_cols[c] = false # Backtrack
        end
        
        return false
    end

    # Initiate DFS from every row node
    for start_row in 1:nr
        # Reset visited arrays for each completely new start node
        fill!(visited_rows, false)
        fill!(visited_cols, false)
        
        if dfs(start_row, start_row, 0, 0, true)
            return true
        end
    end
    
    return false
end

# ==============================================================================
# ALGEBRAIC DECOMPOSITION & DIMENSION
# ==============================================================================

"""
$(TYPEDSIGNATURES)

Decompose the Quasi-Cyclic polynomial matrix into its Fourier/CRT components.

# Notes
* Returns a vector of tuples `(g, A_K)`, where `g` is an irreducible factor of `x^m - 1` 
  and `A_K` is the polynomial matrix evaluated in the extension field `F[x]/<g(x)>`.
* Bypasses the massive memory allocation of `lift(A)`.
"""
function component_matrices(C::AbstractQuasiCyclicCode)
    S = base_ring(C.R) # F[x]
    F = base_ring(S)
    m = C.m
    
    # Ensure semi-simple algebra (m coprime to characteristic)
    gcd(m, Int(characteristic(F))) == 1 || @warn "m is not coprime to field characteristic; decomposition contains nilpotent elements."
    
    facs = factor(gen(S)^m - 1)
    components = Tuple{typeof(gen(S)), MatElem}[]
    
    for (g, _) in facs
        # Construct the extension field (or quotient ring) for the irreducible factor
        K, _ = residue_ring(S, g)
        
        nr, nc = size(C.A)
        A_K = zero_matrix(K, nr, nc)
        
        for r in 1:nr
            for c in 1:nc
                # Map the polynomial into the extension field
                A_K[r, c] = K(lift(C.A[r, c]))
            end
        end
        push!(components, (g, A_K))
    end
    
    return components
end

"""
$(TYPEDSIGNATURES)

Compute the exact dimension `k` of the Quasi-Cyclic code algebraically.

# Notes
* Uses the CRT decomposition to compute the rank over small extension fields.
* Executes in a fraction of the time of `rank(lift(A))`.
"""
function algebraic_dimension(C::AbstractQuasiCyclicCode)
    cache = getfield(C, :cache)
    if !haskey(cache, :algebraic_k)
        total_rank = 0
        comps = component_matrices(C)
        
        for (g, A_K) in comps
            # The dimension contribution is the rank of the component matrix 
            # multiplied by the degree of the field extension.
            ext_deg = degree(g)
            total_rank += ext_deg * rank(A_K)
        end
        
        # If A specifies the Parity Check matrix, k = n - rank
        if C.A_type == :H
            cache[:algebraic_k] = C.n - total_rank
        else
            cache[:algebraic_k] = total_rank
        end
    end
    
    return cache[:algebraic_k]
end

